import { createFeatureSelector, createSelector } from '@ngrx/store';
import { siteAdapter, SiteState } from './site.reducer';


export const selectSites = createFeatureSelector<SiteState>('sites');

const {
          selectIds,
          selectEntities,
          selectAll,
          selectTotal
      } = siteAdapter.getSelectors(selectSites);

export const siteSelectors = {

    // Main selectors generated by the adapter
    selectIds, selectEntities, selectAll, selectTotal,

    selectError:createSelector(
        selectSites,
        (state:SiteState) => state.error
    ),

    selectCurrentSite:createSelector(
        selectSites,
        (state:SiteState) => state.current
    ),

};
